[package]
name = "precision_pool_hooks"
version = "0.1.1"
edition = "2021"

[dependencies]
sbor = "1.2.0"
scrypto = "1.2.0"
common = { git = "https://github.com/ociswap/pools-common", tag = "v1.2.2" }
