name: blueprints
on: push

jobs:
  ociswap_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          default: true
          profile: minimal
          target: wasm32-unknown-unknown
          toolchain: 1.76.0  # should match the rust version of the scrypto-builder

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          cache-all-crates: "true"

      - name: Run main precision pool tests
        run: cargo test --profile=dev --no-fail-fast
      - name: Run test_hook tests
        run: cargo test --profile=dev --no-fail-fast
        working-directory: test_hook
